sudo: false
language: python
cache: pip
matrix:
  include:
    # Django 1.11
    # Wagtail 2.0
    - env: TOXENV=py35-dj111-wt2
      python: 3.5
    - env: TOXENV=py36-dj111-wt2
      python: 3.6

    # Django 2.1
    # Wagtail 2.4
    - env: TOXENV=py35-dj21-wt24
      python: 3.5
    - env: TOXENV=py36-dj21-wt24
      python: 3.6
    - env: TOXENV=py37-dj21-wt24
      python: 3.7
      sudo: true
      dist: xenial

    # Django 2.2
    # Wagtail 2.4
    - env: TOXENV=py35-dj22-wt24
      python: 3.5
    - env: TOXENV=py36-dj22-wt24
      python: 3.6
    - env: TOXENV=py37-dj22-wt24
      python: 3.7
      sudo: true
      dist: xenial

    # Django 2.2
    # Wagtail 2.5
    - env: TOXENV=py35-dj22-wt25
      python: 3.5
    - env: TOXENV=py36-dj22-wt25
      python: 3.6
    - env: TOXENV=py37-dj22-wt25
      python: 3.7
      sudo: true
      dist: xenial

    # Flake 8
    - env: TOXENV=flake8
      python: 3.6


install:
  - pip install tox
script:
  - tox -e $TOXENV
